### ISSUE TITLE
Error with several edges

### ISSUE THREAD

**Issue by svillega** [frewsxcv/graphosaurus#63]
When i add some edges i always get some edge going to /dev/null
http://screencast.com/t/NwOxvRtYdQ

**Comment by frewsxcv** [comment]
Do you have the code you used to generate that? It would be easier to debug if I could replicate it locally

**Comment by svillega** [comment]
Sure Corey, thanks for the fast answer. I really need to find what is happening.
Look a this code
https://gist.github.com/svillega/916f674a0a2e06a9ceb5/9345535c4d83d80c5f2607a3cbfb5d0ddda4e05d

This is what i get
http://screencast.com/t/TbsSh6rSgU

**Comment by frewsxcv** [comment]
Thanks! Just made a few commits fixing a couple bugs (also published a new version on NPM). Let me know if that fixes your issue

**Comment by svillega** [comment]
Thanks Corey! it works perfect now
