### ISSUE TITLE
change node position, adding edges dynamically

### ISSUE THREAD

**Issue by svillega** [frewsxcv/graphosaurus#64]
Hi Corey, just a question.
¿Is it posible to add nodes, change position, or add an edge dynamically?
i don't know if is not possible now or is an error.

Maybe some graph method to redraw?
Thanks! great project. 
Santiago

**Comment by frewsxcv** [comment]
It would be great if this was supported, but as of right now, it is not. I'll leave this open though so I am reminded to complete this.

**Comment by frewsxcv** [comment]
This is now possible. Any modifications done to the `Graph` object result in a rerender of all associated frames.

**Comment by lucacinelli** [comment]
Hi everybody,
is it possible to select a node and move it in the scene by holding it down?
