### ISSUE TITLE
Possibility of bulk data insertion (or wholesale data replacement?)

### ISSUE THREAD

**Issue by mwozniczak** [frewsxcv/graphosaurus#68]

**Comment by frewsxcv** [comment]
Whenever nodes or edges get added to the `Graph`, it triggers a redraw automatically:

* https://github.com/frewsxcv/graphosaurus/blob/2186b851adb75666e613ede6ddc253dfc2aaead6/src/graph.js#L71
* https://github.com/frewsxcv/graphosaurus/blob/2186b851adb75666e613ede6ddc253dfc2aaead6/src/graph.js#L94

So if you change all your data *after* you've already rendered, it's going to result in a lot of draw calls presumably. Yes, this is not ideal if you want to either add or replace the data after you've rendered.

I don't have much time to dedicate to this project nowadays, but if you're looking to extend the functionality, one can just change the `addNode` and `addEdge` to take a `boolean` parameter indicate if the graph should be redrawn.

Let me know if you need any help!

**Comment by mwozniczak** [comment]
I think this issue is more-or-less closeable...?

I mean, right now the nodes/edges are purged wholesale, but deleting _single_ ones was not really the point of _this_ particular issue.

**Comment by frewsxcv** [comment]
https://github.com/frewsxcv/graphosaurus/commit/119e1836d8a7751febea5d8441fdfbad3951b296 allowed for removal of *all* nodes. we should allow for specific node removal

**Comment by frewsxcv** [comment]
Sounds good
