### ISSUE TITLE
Nodes/edges not fully deleted and leaking into memory?

### ISSUE THREAD

**Issue by mwozniczak** [frewsxcv/graphosaurus#72]
Seems like the functions for purging nodes and edges (which, admittedly, I added) are missing deletion of some representation(s?) of themselves in the data, causing the memory to slowly but surely overflow on multiple addition/deletion operations.

**Comment by mwozniczak** [comment]
Sorry, nevermind, seems like it was caused by me goofing up in cleaning up _my_ data, nevermind probably!

**Comment by frewsxcv** [comment]
> Sorry, nevermind, seems like it was caused by me goofing up in cleaning up my data, nevermind probably!

No problem! Feel free to reopen if you encounter the memory leaking again
